spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: root

springdoc:
  swagger-ui:
    path: /documentation
  api-docs:
    path: /api-docs